name: graphql_fetch_country
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  graphql: ^5.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  firebase_core: ^1.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
